# Provides a lightweight C/C++ compiler environment for submitted code.
FROM alpine:3.9
WORKDIR /usr/cpp
RUN apk add build-base

#docker build -t cpp:v1 .
# run this command while in the cpp directory
